MiniRedSocial/Controllers/FriendShipController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MiniRedSocial.Core.Application.Interfaces.Services;
using MiniRedSocial.Core.Application.ViewModels.Friendship;
using MiniRedSocial.Core.Application.ViewModels.Publication;
using MiniRedSocial.infrastructure.Identity.Entities;

namespace MiniRedSocial.Controllers
{
    public class FriendShipController : Controller
    {
        private readonly IUserService _userService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IPublicationService _publicationService;
        private readonly IAccountService _accountService;
        private readonly IMessageService _messageService;
        private readonly IFriendshipService _friendshipService;
        private readonly IHiloService _hiloService;

        public FriendShipController(IAccountService accountService,IFriendshipService friendshipService,IUserService userService, IPublicationService publicationService, IMessageService messageService, IHiloService hiloService, UserManager<ApplicationUser> userManager)
        {
            _publicationService = publicationService;
            _accountService = accountService;
            _messageService = messageService;
            _friendshipService = friendshipService;
            _hiloService = hiloService;
            _userManager = userManager;
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            // Obtener las amistades del usuario actual
            List<FriendshipViewModel> userFriendships = await _friendshipService.GetFriendshipsByUserId(user.Id);

            // Obtener los IDs de amigos del usuario actual
            List<string> friendIds = userFriendships.Select(f => f.FriendId == user.Id ? f.UserId : f.FriendId).ToList();

            List<PublicationViewModel> publicaciones = await _publicationService.GetAllViewModel();

            List<PublicationViewModel> publicacionesFiltradas = publicaciones
                .Where(publicacion => friendIds.Contains(publicacion.UserId))
                .ToList();

            foreach (var publicacion in publicacionesFiltradas)
            {
                publicacion.Messages = await _messageService.GetAllViewModelByPublicationId(publicacion.Id);

                foreach (var mensaje in publicacion.Messages)
                {
                    mensaje.Respuestas = await _hiloService.GetAllViewModelByPublicationId(mensaje.Id);
                }
            }

            return View(publicacionesFiltradas);
        }

        [HttpGet]
        public IActionResult AddFriend()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddFriend(string username)
        {
            var CurrentUser = await _userManager.GetUserAsync(User);

            string FriendUser = await _accountService.GetUserByUsernameAsync(username);

            if (FriendUser == null)
            {
                ModelState.AddModelError(string.Empty, $"No se encontró ningún usuario con el nombre de usuario '{username}'.");
                return View();
            }

            var areFriends = await _friendshipService.AreFriends(CurrentUser.Id, FriendUser);

            if (areFriends)
            {
                return Conflict();
            }

            var frienship = new SaveFriendshipViewModel
            {
                UserId = CurrentUser.Id,
                FriendId = FriendUser
            };

            await _friendshipService.Add(frienship);

            return RedirectToAction("Index", "FriendShip");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFriend(int friendshipId)
        {
            var currentUser = await _userManager.GetUserAsync(User);

            await _friendshipService.Delete(friendshipId);

            return RedirectToAction("Index", "FriendShip");
        }

    }
}

MiniRedSocial/Controllers/PublicationController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MiniRedSocial.Core.Application.Helpers;
using MiniRedSocial.Core.Application.Interfaces.Services;
using MiniRedSocial.Core.Application.ViewModels.Publication;
using MiniRedSocial.infrastructure.Identity.Entities;

namespace MiniRedSocial.Controllers
{
    public class PublicationController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IPublicationService _publicationService;
        private readonly IMessageService _messageService;
        private readonly IHiloService _hiloService;

        public PublicationController (UserManager<ApplicationUser> userManager, IPublicationService publicationService, IMessageService messageService, IHiloService hiloService)
        {
            _userManager = userManager;
            _publicationService = publicationService;
            _messageService = messageService;
            _hiloService = hiloService;
        }

        [HttpGet]
        public IActionResult SelectType()
        {
            return View( new SelectTipeViewModel());
        }

        [HttpPost]
        public IActionResult SelectType(SelectTipeViewModel vm)
        {
            if(!ModelState.IsValid)
            {
                return View(vm);
            }

            SavePublicationViewModel viewModel = new SavePublicationViewModel();

            viewModel.Tipe = vm.Tipe;

            return RedirectToAction(nameof(CreatePublication), new { tipe = viewModel.Tipe });
        }

        [HttpGet]
        public IActionResult CreatePublication(int tipe)
        {
            SavePublicationViewModel viewModel = new SavePublicationViewModel();
            viewModel.Tipe = tipe;

            if (viewModel.Tipe <= 0 || viewModel.Tipe > 3)
            {
                return View(nameof(SelectType));
            }

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePublication(SavePublicationViewModel vm)
        {
            if(!ModelState.IsValid)
            {
                return View(vm);
            }

            var user = await _userManager.GetUserAsync(User);

            vm.UserId = user.Id;
            vm.Date = DateTime.Now;

            if(vm.Tipe == 3)
            {
                vm.Url = FileManager.GetEmbeddedLink(vm.Url);
            }

            SavePublicationViewModel publication = await _publicationService.Add(vm);

            if (publication.Tipe == 2)
            {
                if(publication != null && publication.Id != 0)
                {
                    publication.Url = FileManager.UploadFile(vm.File, publication.Id.ToString());

                    await _publicationService.Update(publication, publication.Id);
                }
                
            }


            return RedirectToRoute(new { controller = "Home", action = "Index" });
        }


        [HttpGet]
        public async Task<IActionResult> EliminarPublicacion(int id)
        {
            return View(await _publicationService.GetByIdSaveViewModel(id));
        }

        [HttpPost, ActionName("EliminarPublicacion")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Eliminar(int id)
        {

            await _publicationService.Delete(id);
            string basePath = $"/Images/Publications/{id}";
            string path = Path.Combine(Directory.GetCurrentDirectory(), $"wwwroot{basePath}");

            if (Directory.Exists(path))
            {
                DirectoryInfo directory = new(path);

                foreach (FileInfo file in directory.GetFiles())
                {
                    file.Delete();
                }
                foreach (DirectoryInfo folder in directory.GetDirectories())
                {
                    folder.Delete(true);
                }

            }

            return RedirectToRoute(new { controller = "Home", action = "Index" });
        }
    }
}

MiniRedSocial/Views/FriendShip/AddFriend.cshtml
@{
    ViewData["Title"] = " Agregar Amigos";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-6 offset-3">
            <div class="card">
                <div class="card-header bg-dark text-light">
                    <h4>Agregar Amigos</h4>
                </div>
                <div class="card-body">
                    <form method="post" asp-controller="FriendShip" asp-action="AddFriend">

                        <div class="mb-3">
                            <label for="username" class="form-label">Nombre de usuario:</label>
                            <input type="text" id="username" name="username" class="form-control" for="username" />
                            
                        </div>

                        <button type="submit" class="btn btn-primary">Agregar</button>
                        <a asp-controller="FriendShip" asp-action="index" class="btn btn-warning">Volver atrás</a>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

MiniRedSocial/Views/FriendShip/Index.cshtml
@using MiniRedSocial.Core.Application.ViewModels.Publication;
@using MiniRedSocial.Core.Application.Enums;
@model List<PublicationViewModel>;

@{
    ViewData["Title"] = "Amigos";
}

<div class="row mb-3">
    <div class="col-3 offset-9">
        <a asp-action="AddFriend" asp-controller="FriendShip" class="btn btn-outline-secondary d-block mx-auto">
            <i class="bi bi-file-plus-fill"></i> Agregar Amigo
        </a>
    </div>
</div>

<div class="row">
    <h1 class="display-4">Publicaciones</h1>
    <div class="offset-12">
        @if (Model != null && Model.Count > 0)
        {
            @foreach (PublicationViewModel publication in Model)
            {
                <div class="mb-3" style="border: solid 2px black; padding: 5px; border-radius: 5px;">

                    @if (publication.Tipe == (int)MessageTipe.Text)
                    {
                        <div class="mb-3">
                            <img src="@publication.UserImg" alt="Imagen" style="display: inline-block; margin: 0 auto; height: auto; max-width: 50px; border-radius: 50%;">
                            <p class="mb-2">@publication.Date</p>
                            <p>@publication.Content</p>
                        </div>
                    }

                    @if (publication.Tipe == (int)MessageTipe.Image)
                    {
                        <div class="mb-3" style="text-align: center;">
                            <div class="text-overlay" style="text-align: left;">
                                <img src="@publication.UserImg" alt="Imagen" style="display: inline-block; margin: 0 auto; height: auto; max-width: 50px; border-radius: 50%;">
                                <p>@publication.Date</p>
                                <p>@publication.Content</p>
                            </div>
                            <img src="@publication.Url" alt="Imagen" style="display: inline-block; margin: 0 auto; height: auto; max-width: 400px;">
                        </div>
                    }

                    @if (publication.Tipe == (int)MessageTipe.Video)
                    {
                        <div class="mb-3" style="text-align: center;">
                            <div class="text-overlay" style="text-align: left;">
                                <img src="@publication.UserImg" alt="Imagen" style="display: inline-block; margin: 0 auto; height: auto; max-width: 50px; border-radius: 50%;">
                                <p>@publication.Date</p>
                                <p>@publication.Content</p>
                            </div>
                            <iframe  src="@publication.Url" class="youtube-player" id="youtube-player-@publication.Id" width="450" height="250" frameborder="0" allowfullscreen style="display: inline-block; margin: 0 auto;"></iframe>
                        </div>
                    }

                    <div style="display: flex; justify-content: space-between;">
                        <a class="btn btn-outline-danger btn-sm" asp-action="EliminarPublicacion" asp-controller="Publication" asp-route-id="@publication.Id">
                            Elimar Publicacion
                        </a>
                        <a class="btn btn-outline-primary btn-sm" asp-action="VerComentarios" asp-controller="Message" asp-route-id="@publication.Id">
                            @((publication.Messages.Count() > 0) ? $"Comentarios ({publication.Messages.Count()})" : "Agregar comentario")
                        </a>
                    </div>

                </div>
            }
        }
        else
        {
            <p>No hay publicaciones</p>
        }
    </div>
</div>